# Generated by Django 3.1 on 2020-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_type',
        ),
        migrations.AddField(
            model_name='car',
            name='car_name',
            field=models.CharField(default='Ford', max_length=50),
        ),
    ]
